### PR TITLE
Fix encryption: ensure randomize iv

### LINKED ISSUE #27: [Audit] Fix storage encryption
Ensure to have distinct IV be used for every AES-GCM operation

### PR DESCRIPTION
**Pull request by codsay**
Fixes #27 

- [x] Tests pass

### CODE REVIEW

File: src/cryptography/utils/aes-utils.ts [hunk 1]
```diff
@@ -22,19 +42,21 @@ export class AESUtils {
...
     if (!value) throw new Error("Value is required")
     if (!mode) throw new Error("Encrypt mode is required")
 
     const crypto = CryptoUtils.getCrypto();
-    iv = iv || CryptoUtils.randomBytes(16);
+    
+    const salt = CryptoUtils.randomBytes(16);
+    const iv = CryptoUtils.randomBytes(16);
+
+    const keyBytes = CryptoUtils.scrypt(password, salt);
```
Comment (djhahe) [inline src/cryptography/utils/aes-utils.ts]: duplicated with l91-92, could be extracted to reuse

**Review by djhahe — APPROVED** [review]
